function [v] = logh(n,alpha,b,y,lam,phi,psi,sig_a2,sig_l2,sig_p2)
v = -0.5*n*lam-0.5*exp(alpha)*sum(b)-0.5*sum(y.*y.*exp(-lam-exp(alpha)*b)) ...
    -0.5*sum((b(2:end)-b(1:end-1)).^2)-0.5*log(1-phi*phi) ...
    -0.5*(1-phi*phi)*b(1)*b(1)-alpha*alpha/(2*sig_a2)-lam*lam/(2*sig_l2)-psi*psi/(2*sig_p2);
end