function [v] = logq(alpha,lambda,sigma2,gamma2,muaq,invsigaq,mulq,invsiglq,as,bs,ag,bg,m,d)
    v = m*logdet(invsigaq,'chol')-0.5*(alpha-muaq).'*invsigaq*(alpha-muaq) ...
        -d/2*logdet(invsiglq,'chol')-0.5*(lambda-mulq).'*invsiglq*(lambda-mulq) ...
        +as*log(bs)-gammaln(as)-(as+1)*log(sigma2)-bs/sigma2 ...
        +ag*log(bg)-gammaln(ag)-(ag+1)*log(gamma2)-bg/gamma2;
end